name: italala-js-server

services:
  pg:
    image: bitnami/postgresql:17.0.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker-italala
      - POSTGRES_PASSWORD=dockeritalala
      - POSTGRES_DB=italala